---
title: "NFL Scores Week 20"
author: "Daniel Baller"
date: "Sept 3, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NFL Scores from cbssports.com

```{r}
library(tidyverse)
library(stringr)
library(XML)
library(xml2)
library(purrr)
library(rvest)

?html_node


# Only thing you need to change (add additional week)

week = list(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) # List of weeks

url = "https://www.cbssports.com/nfl/schedule/2020/regular/"  #base URL

list_of_pages = function(x){
  str_c(url,x)
}

scores = function(week, url){
  
  stats = url%>%
    read_html()%>%
    html_nodes(".CellGame a")%>%
    html_text() %>% 
    matrix(ncol = 1, byrow = TRUE) %>%
    as.data.frame()%>%
    rename(`Score` = V1) %>% 
    separate(Score, sep = " ", into = c("TM1","Score1", "vs", "TM2", "Score2")) %>% 
    mutate(week = week)
}

week%>%
  map(list_of_pages) %>% 
  map2(week,.,scores)%>%
  bind_rows() %>% 
  write_csv(glue::glue("../CSV_Data_Files/NFL_Scores_{length(week)}.csv"))
```
Adding in the playoffs
```{r}
library(tidyverse)
library(stringr)
library(XML)
library(xml2)
library(purrr)
library(rvest)

# Only thing you need to change (add additional week)

week = list(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17) # List of weeks
week_post = list(18,19,20) # List of weeks

url = "https://www.cbssports.com/nfl/schedule/2020/regular/"  #base URL
url_post = "https://www.cbssports.com/nfl/schedule/2020/postseason/"  #base URL

list_of_pages = function(x){
  str_c(url,x)
}

list_of_pages_post = function(x){
  str_c(url_post,x)
}

scores = function(week, url){
  
  stats = url%>%
    read_html()%>%
    html_nodes(".CellGame a")%>%
    html_text() %>% 
    matrix(ncol = 1, byrow = TRUE) %>%
    as.data.frame()%>%
    rename(`Score` = V1) %>% 
    separate(Score, sep = " ", into = c("TM1","Score1", "vs", "TM2", "Score2")) %>% 
    mutate(week = week)
}

scores_post = function(week, url_post){
  
  stats = url_post%>%
    read_html()%>%
    html_nodes(".CellGame a")%>%
    html_text() %>% 
    matrix(ncol = 1, byrow = TRUE) %>%
    as.data.frame()%>%
    rename(`Score` = V1) %>% 
    separate(Score, sep = " ", into = c("TM1","Score1", "vs", "TM2", "Score2")) %>% 
    mutate(week = week)
}

reg = week%>%
  map(list_of_pages) %>% 
  map2(week,.,scores)%>%
  bind_rows()

post = week_post%>%
  map(list_of_pages_post) %>% 
  map2(week_post,.,scores_post)%>%
  bind_rows()

bind_rows(reg, post) %>%
  write_csv(glue::glue("../CSV_Data_Files/NFL_Scores_{length(week)+length(week_post)}.csv"))
```

```{r}
read_html("https://www.cbssports.com/nfl/schedule/2020/regular/1/")%>%
    html_nodes(".CellGame a , .TeamName a")%>%
    html_text() %>% 
    matrix(ncol = 3, byrow = TRUE) %>%
    as.data.frame()%>%
    rename(`Away Team` = V1, `Home Team` = V2, `Score` = V3) %>% 
    separate(Score, sep = " ", into = c("TM1","Score1", "vs", "TM2", "Score2"))
```

home teams

```{r}
# Only thing you need to change (add additional week)

url = "https://www.cbssports.com/nfl/schedule/2020/regular/"  #base URL

list_of_pages = function(x){
  str_c(url,x)
}

scores = function(week, url){
  
  stats = url%>%
    read_html()%>%
    html_nodes(".TableBase-bodyTd+ .TableBase-bodyTd .TeamName a")%>%
    html_text() %>% 
    matrix(ncol = 1, byrow = TRUE) %>%
    as.data.frame()%>%
    rename("home_team" = V1) %>% 
    #separate(Score, sep = " ", into = c("TM1","Score1", "vs", "TM2", "Score2")) %>% 
    mutate(week = week)
}

week%>%
  map(list_of_pages) %>% 
  map2(week,.,scores)%>%
  bind_rows() %>% 
  write_csv(glue::glue("../CSV_Data_Files/NFL_Scores_{length(week)}_home.csv"))
```

```{r}
read_html("https://www.cbssports.com/nfl/schedule/2020/regular/1/")%>%
    html_nodes(".CellGame a")%>%
    html_text() %>% 
    matrix(ncol = 1, byrow = TRUE) %>%
    as.data.frame()%>%
    rename(`Score` = V1) %>% 
    separate(Score, sep = " ", into = c("TM1","Score1", "vs", "TM2", "Score2"))
```